version: '3'
services:
  elasticsearch:
    build: elasticsearch
    ports:
      - "9200:9200"
    expose:
      - "9300"
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  kibana:
    build: kibana
    ports:
      - "5601:5601"

#volumes:
#  es-data:
#    driver: local
