version: '3'
services:
  elasticsearch:
    build: elasticsearch
    container_name: fb_elasticsearch
    ports:
      - "9200:9200"
    expose:
      - "9300"
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  logstash:
    build: logstash
    container_name: fb_logstash
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./log:/var/log
    depends_on:
      - elasticsearch

  kibana:
    build: kibana
    container_name: fb_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

#volumes:
#  es-data:
#    driver: local
